[package]
name = "opengl-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
thiserror = "1.0.51"
image = "0.24.7"
nalgebra-glm = "0.18.0"
glfw = "0.54.0"
tobj = "4.0.0"